### ISSUE TITLE
Undefined constant error

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/passphrase_policy#2]
`Notice: Use of undefined constant BACKDROP_AUTHENTICATED_RID - assumed 'BACKDROP_AUTHENTICATED_RID' in passphrase_policy_form_alter() (line 95 of /httpdocs/modules/passphrase_policy/passphrase_policy.module).`

**Comment by deekayen** [comment]
I guess we need the equivalent of https://api.drupal.org/api/drupal/includes%21bootstrap.inc/constant/DRUPAL_AUTHENTICATED_RID/7.x

**Comment by herbdool** [comment]
I think it's just BACKDROP_AUTHENTICATED_ROLE

**Comment by deekayen** [comment]
Would you like to get credit with a pull request or shall I just fix it?

**Comment by herbdool** [comment]
Thank you but not necessary. Thanks for the fix
