### ISSUE TITLE
Non-Backdrop tags

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/passphrase_policy#3]
Thanks again for the quick response on the other issue @deekayen. I'm adding this because Github is suggesting there are 52 releases for this project because the vast majority of them are not related to Backdrop. I suggest deleting all the tags that precede 1.x-1.0.0

**Comment by deekayen** [comment]
Cleaned. I did it through the GitHub web interface so hopefully will remember to clean my macbook tags before I push again.
