### ISSUE TITLE
Make password requirements work on the password reset form

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/passphrase_policy#5]
Password requirements work well on user edit pages like `user/1/edit`. However, when requesting a password on the`/user/password` page, then clicking on the sent out link and entering simple passwords without special characters or digits like, for example, `iUvoWZbtbJ` on the reset form goes through:

![Screen Shot 2020-01-17 at 8 21 36 PM](https://user-images.githubusercontent.com/56604405/72657861-1da52b80-3967-11ea-9163-a66df2c436fc.png)

Please make the Passphrase policy module work on password reset form.

**Comment by indigoxela** [comment]
Confirmed, on password reset form any (stupid) password can get set.

**Comment by indigoxela** [comment]
I've created a quick [PR](https://github.com/backdrop-contrib/passphrase_policy/pull/6).
This module really needs some more loving care, though.

I'm not sure, if there's a maintainer, at least the README doesn't list one. We might need help from the @backdrop-contrib/bug-squad 

Or are you around @deekayen ?

**Comment by deekayen** [comment]
I'm around-ish. The README is correct in listing None for maintainer.

**Comment by alanmels** [comment]
Works fine now. Ready to be released. @deekayen could you please make another release or give your perm and I'll do it.

**Comment by deekayen** [comment]
@alanmels go ahead

**Comment by alanmels** [comment]
Done: https://github.com/backdrop-contrib/passphrase_policy/releases/tag/1.x-1.1.3 I could take over the maintainership of the module if you want. Thanks!

**Comment by deekayen** [comment]
@alanmels I sort of thought of it as community property. It's had so many contributors over its life. I won't stand in your way if you put your name on the maintainer line, but this is like the first patch its needed in 2 years.

**Comment by alanmels** [comment]
I won't impose myself by putting my name in the list, so leave it as is for now. I believe with D7 EOL approaching and more D7 sites shifting to Backdrop this module will gain its traction. Ideally it should get to core, IMO.

**Comment by herbdool** [comment]
@alanmels @deekayen I say Alan being a maintainer is a good idea. Even though the community contributes, we still need to know who will be managing the PRs and adding new releases.
